


language: objective-c

osx_image: xcode8

xcode_project: TravisStepA.xcworkspace

xcode_scheme: TravisStepA

xcode_sdk: iphonesimulator10.0

script: xcodebuild -workspace TravisStepA.xcworkspace -scheme TravisStepA -sdk iphonesimulator10.0